import Head from 'next/head'
import Image from 'next/image'
import Dashboard from '../components/Dashboard'
import Login from '../components/Login'
// import UserDashboard from '../components/UserDashboard'
import { useAuth } from '../context/AuthContext'

export default function Home(props) {
    const { currentlySelectedExercise } = props
    const { currentUser } = useAuth()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!currentUser && <Login />}
            {currentUser && (
                <Dashboard
                    currentlySelectedExercise={currentlySelectedExercise}
                />
            )}
        </>
    )
}
